version: "3.7"
services:
  db:
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    container_name: investimentos_api
    build: 
      context: .
      dockerfile: Dockerfile
      target: app
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db

volumes:
  postgres_data: